# Generated by Django 6.0.3 on 2026-03-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(max_length=500),
        ),
    ]
