# Generated by Django 6.0.3 on 2026-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Drinks'), ('electronics', 'Electronics'), ('office', 'Office Supplies'), ('clothing', 'Clothing & Accessories'), ('home', 'Home & Garden'), ('toys', 'Toys & Games '), ('health', 'Health & Beauty'), ('sports', 'Sports & Outdoors'), ('automotive', 'Automotive'), ('books', 'Books & Media'), ('miscKitchen', 'Kitchen & Dining'), ('sex-toys', 'Sex-Toys'), ('rent-house', 'House-Rent'), ('car-sales', 'Car-Sales'), ('kitchen-items', 'Kitchen-Items')], max_length=20),
        ),
    ]
