# Generated by Django 6.0.3 on 2026-04-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_mart', '0009_alter_order_status_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Drinks'), ('electronics', 'Electronics'), ('office', 'Office Supplies'), ('style&fashion', 'Style & Fashion'), ('home', 'Home & Garden'), ('toys', 'Toys & Games '), ('health', 'Health & Beauty'), ('sports', 'Sports & Outdoors'), ('automotive', 'Automotive'), ('books', 'Books & Media'), ('miscKitchen', 'Kitchen & Dining'), ('sex-toys', 'Sex-Toys'), ('rent-house', 'House-Rent'), ('car-sales', 'Car-Sales'), ('kitchen-items', 'Kitchen-Items')], max_length=20),
        ),
    ]
